apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: donet-quay-annotation-0325 
  janus-idp.io/tekton: donet-quay-annotation-0325
  backstage.io/kubernetes-id: donet-quay-annotation-0325
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: donet-quay-annotation-0325
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  